# Generated by Django 6.0.3 on 2026-03-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiBerekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gewicht', models.FloatField()),
                ('lengte', models.FloatField()),
                ('bmi_waarde', models.FloatField()),
                ('categorie', models.CharField(max_length=50)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
